### ISSUE TITLE
ceres-solver 2.1.0 failed to build against suite-sparse 7.2.0

### ISSUE THREAD

**Issue by chenrui333** [ceres-solver/ceres-solver#1009]
👋 while trying to upgrade suite-sparse 7.2.0, I found the cmake build cannot find cxsparse target

```
  CMake Error at internal/ceres/CMakeLists.txt:329 (target_link_libraries):
    Target "ceres" links to:
  
      CXSparse::CXSparse
```

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/6213969975/job/16865503527?pr=143338
relates to https://github.com/Homebrew/homebrew-core/pull/143338

On top of it, when would be the next release for ceres-solver? Thanks!

**Comment by sandwichmaker** [comment]
Should be fixed at head. We will likely make a point release to deal with this.

**Comment by sandwichmaker** [comment]
We are working on a 2.2.0 release as we speak.

**Comment by sandwichmaker** [comment]
2.2.0rc1 is out for testing.

**Comment by thierry-FreeBSD** [comment]
> Should be fixed at head. We will likely make a point release to deal with this.

Actually, it is not yet fixed. With the patch in https://github.com/ceres-solver/ceres-solver/commit/9cca671273c2f205ca7350422f48b7b119c5dd78 the hereunder error still exists:

```
CMake Error at internal/ceres/CMakeLists.txt:329 (target_link_libraries):
  Target "ceres" links to:

    CXSparse::CXSparse

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



CMake Error at internal/ceres/CMakeLists.txt:295 (target_link_libraries):
  Target "ceres_static" links to:

    CXSparse::CXSparse

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

**Comment by sandwichmaker** [comment]
We have 2.2.0rc2 out for testing. It should be released by next Monday.
Please rest it and see if it works for you.

Sameer

**Comment by thierry-FreeBSD** [comment]
2.2.0rc1 builds fine on FreeBSD, but the compilation of [OpenTURNS](https://openturns.github.io/www/)  fails with it:
```
FAILED: lib/src/CMakeFiles/OT.dir/Base/Optim/Ceres.cxx.o 
/usr/local/bin/clang++12 -DGFLAGS_IS_A_DLL=0 -DGLOG_CUSTOM_PREFIX_SUPPORT -DH5_BUILT_AS_DYNAMIC_LIB -DNLOPT_DLL -DOT_DLL_EXPORTS -DOT_EXPORTS -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Process -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/StatTests -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Algorithm/WeightedExperiments -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Algorithm/Transformation/ProcessTransformation -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Algorithm/Transformation/Rosenblatt -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Algorithm/Transformation/NatafIndependentCopula -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Algorithm/Transformation/NatafEllipticalDistribution -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Algorithm/Transformation/NatafEllipticalCopula -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Algorithm/Transformation/MarginalTransformation -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Algorithm/Transformation -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Algorithm/Simulation -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Algorithm/Sensitivity -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Algorithm/OrthogonalBasis -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Algorithm/Optimization -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Algorithm/MetaModel/LinearModel -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Algorithm/MetaModel/TensorApproximation -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Algorithm/MetaModel/Kriging -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Algorithm/MetaModel/FunctionalChaos -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Algorithm/MetaModel -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Algorithm/Classification -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Algorithm/Analytical -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Algorithm -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Distribution -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Model -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty/Bayesian -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Uncertainty -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Base/IterativeStat -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Base/Type -I/usr/ports/math/openturns/work/.build/lib/src/Base/Stat -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Base/Stat -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Base/Solver -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Base/Optim -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Base/MetaModel -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Base/Graph -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Base/Geom -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Base/Func/SpecFunc -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Base/Func -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Base/Experiments -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Base/Diff/Ev3 -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Base/Diff -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Base/Common -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Base/Algo -I/usr/ports/math/openturns/work/openturns-1.20/lib/src/Base -I/usr/ports/math/openturns/work/openturns-1.20/lib/src -I/usr/ports/math/openturns/work/.build/lib/include -I/usr/ports/math/openturns/work/openturns-1.20/lib/include -I/usr/local/include/libxml2 -I/usr/local/include/cminpack-1 -I/usr/local/include/coin -isystem /usr/local/include/coin-or -isystem /usr/local/include/eigen3 -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -isystem /usr/local/include  -DNDEBUG -std=gnu++17 -fPIC -pthread -fopenmp=libomp -MD -MT lib/src/CMakeFiles/OT.dir/Base/Optim/Ceres.cxx.o -MF lib/src/CMakeFiles/OT.dir/Base/Optim/Ceres.cxx.o.d -o lib/src/CMakeFiles/OT.dir/Base/Optim/Ceres.cxx.o -c /usr/ports/math/openturns/work/openturns-1.20/lib/src/Base/Optim/Ceres.cxx
/usr/ports/math/openturns/work/openturns-1.20/lib/src/Base/Optim/Ceres.cxx:345:15: error: no member named 'use_postordering' in 'ceres::Solver::Options'
      options.use_postordering = ResourceMap::GetAsBool("Ceres-use_postordering");
      ~~~~~~~ ^
1 error generated.
```
I shall try RC2 ASAP.

**Comment by sandwichmaker** [comment]
I believe that's a deprecated option being used in the code.
use_postordering doesn't exist anymore.

**Comment by thierry-FreeBSD** [comment]
Yes, with the hereunder patch OpenTURNS is fine:
```
--- lib/src/Base/Optim/Ceres.cxx.orig   2022-11-08 10:49:19 UTC
+++ lib/src/Base/Optim/Ceres.cxx
@@ -341,8 +341,6 @@ void Ceres::run()
       throw InvalidArgumentException(HERE) << "Invalid value for sparse_linear_algebra_library_type";
     if (ResourceMap::HasKey("Ceres-use_explicit_schur_complement"))
       options.use_explicit_schur_complement = ResourceMap::GetAsBool("Ceres-use_explicit_schur_complement");
-    if (ResourceMap::HasKey("Ceres-use_postordering"))
-      options.use_postordering = ResourceMap::GetAsBool("Ceres-use_postordering");
     if (ResourceMap::HasKey("Ceres-dynamic_sparsity"))
       options.dynamic_sparsity = ResourceMap::GetAsBool("Ceres-dynamic_sparsity");
     if (ResourceMap::HasKey("Ceres-min_linear_solver_iterations"))

```
