### ISSUE TITLE
invert_psd_matrix_test fails on Debian Sid, amd64

### ISSUE THREAD

**Issue by debalance** [ceres-solver/ceres-solver#304]
Trying to package 1.13.0 RC1 for Debian, I encounter one failing unit test:

> 36/75 Test #39: invert_psd_matrix_test .......................***Exception: Other  0.12 sec
Running main() from gmock_main.cc
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from InvertPSDMatrix
[ RUN      ] InvertPSDMatrix.Identity3x3
[       OK ] InvertPSDMatrix.Identity3x3 (0 ms)
[ RUN      ] InvertPSDMatrix.FullRank5x5
[       OK ] InvertPSDMatrix.FullRank5x5 (0 ms)
[ RUN      ] InvertPSDMatrix.RankDeficient5x5
invert_psd_matrix_test: /usr/include/eigen3/Eigen/src/SVD/JacobiSVD.h:637: void Eigen::JacobiSVD<MatrixType, QRPreconditioner>::allocate(Eigen::Index, Eigen::Index, unsigned int) [with _MatrixType = Eigen::Matrix<double, 5, 5, 1, 5, 5>; int QRPreconditioner = 2; Eigen::Index = long int]: Assertion `(!(m_computeThinU || m_computeThinV) || (MatrixType::ColsAtCompileTime==Dynamic)) && "JacobiSVD: thin U and V are only available when your matrix has a dynamic number of columns."' failed.

Debian unstable currently has Eigen 3.3.4.

**Comment by sandwichmaker** [comment]
curiously, this does not seem to be a problem using eigen 3.3.4 on the mac using homebrew.

**Comment by sandwichmaker** [comment]
@debalance could I get more details, say the cmake log here? I am unable to replicate this failure on eigen 3.2.0-8 on ubuntu or on eigen 3.3.4 on macos.

**Comment by debalance** [comment]
Full build log attached. The build happens in a clean chroot with only the build dependencies installed.

[ceres-solver_1.13.0\~rc1\~dfsg0-1_amd64.build.txt](https://github.com/ceres-solver/ceres-solver/files/1167915/ceres-solver_1.13.0.rc1.dfsg0-1_amd64.build.txt)

Let me know if I can make the build more verbose somehow.

**Comment by leokoppel** [comment]
I reproduced with Eigen 3.3.2. The exception occurs with `-DCMAKE_BUILD_TYPE=None` or `Debug `, not with `Release`. [Build log](https://launchpadlibrarian.net/330456364/buildlog_ubuntu-xenial-amd64.ceres-solver_1.13.0.rc1-1~xenial1_BUILDING.txt.gz)

**Comment by sergiud** [comment]
That's an assert rather than an exception. This is why it's triggered in debug builds only.

Looking at the google test log, it seems `Eigen::JacobiSVD` with `Eigen::ComputeThinU` and/or `Eigen::ComputeThinV` is used on a fixed size matrix which is [incorrect](https://eigen.tuxfamily.org/dox/classEigen_1_1JacobiSVD.html#a5dab376cc86cf0d36674bcdad4af3f5a).

**Comment by sandwichmaker** [comment]
thanks for the reproduction, looking now.  really weird that the test passes though.

**Comment by debalance** [comment]
I can confirm that the test doesn't fail if setting -DCMAKE_BUILD_TYPE=Release

**Comment by sandwichmaker** [comment]
https://ceres-solver-review.googlesource.com/#/c/10820/ is out for review.

**Comment by sandwichmaker** [comment]
@debalance this should be fixed. Also I am curious why is the debian build not in release mode? Please close this issue when you have a verification.

**Comment by debalance** [comment]
Confirmed, the issue is solved.

Until this issue came up I wasn't aware of the different CMAKE_BUILD_TYPE variants, so simply didn't set any in the package build. I don't think there's anything in the docs regarding this, at least I didn't find anything. I'm now setting the package build to release mode.

What I would like to know is, why did this issue not surface during release mode?

**Comment by sandwichmaker** [comment]
I am not sure. The assert only fires in debug mode but I was able to get
the correct answer for fixed size matrices. Maybe I did not hit the corner
case where the assert is actually trying to protect from? In any case that
branch of the code is not used by anyone yet.

**Comment by leokoppel** [comment]
I think it is because you are doing SVD on a square matrix, so Eigen does not try to resize anything. "Thin" only makes a difference for a non-square matrix.

**Comment by sandwichmaker** [comment]
Thin should make a difference for rank deficient square matrices, no? hmm you maybe right. I will check.

**Comment by sandwichmaker** [comment]
@leokoppel you are right. The problem is not fixed size but my desire to use thin svd which is pointless here because the matrices will always be square.

**Comment by leokoppel** [comment]
I see what you mean; rank-deficient does mean only part of U and V is needed to calculate the inverse. It's just that Eigen does not consider rank when choosing the dimensions of the return values, even with "thin" option.

[Here](https://bitbucket.org/eigen/eigen/src/8d1ccfd9c5a0bf1a662bd0fe35858f4e527d2bac/Eigen/src/SVD/SVDBase.h?at=default&fileviewer=file-view-default#SVDBase.h-258) is how Eigen internally calculates the inverse in `JacobiSVD::solve()`:

```cpp
  // A = U S V^*
  // So A^{-1} = V S^{-1} U^*

  Matrix<Scalar, Dynamic, RhsType::ColsAtCompileTime, 0, MatrixType::MaxRowsAtCompileTime, RhsType::MaxColsAtCompileTime> tmp;
  Index l_rank = rank();
  tmp.noalias() =  m_matrixU.leftCols(l_rank).adjoint() * rhs;
  tmp = m_singularValues.head(l_rank).asDiagonal().inverse() * tmp;
  dst = m_matrixV.leftCols(l_rank) * tmp;
```

**Comment by sandwichmaker** [comment]
Thanks @leokoppel I will take a look.
